### ISSUE TITLE
部署服务遇到的问题

### ISSUE THREAD

**Issue by layman404** [cheikh-wang/LazyWaimai-Web#4]
我在阿里云搭了一个LAMP服务器（centos 6.9，php 5.6，mysql 5.7），把web服务和api服务全都部署上了服务器。
1.在测试运行发现，web服务输入手机号码，显示手机号码不存在，换了多个号码也是如此。
所有配置全都按照文档要求进行安装，但还是出现了一些问题，不知是什么原因，希望您能够指点。

**Comment by cheikh-wang** [comment]
检查一下如下几个可能的问题：
1.是否有导入数据库文件
2.输入的手机号数据库的admin表中是否存在，默认账号：admin，123456
3.如果是自行部署，请先申请云之讯的短信验证服务和七牛的存储空间服务，按照README中的说明进行配置

**Comment by layman404** [comment]
问题解决了，手机号在admin表中不存在，现已经调试好了，谢谢！
